version: '3'
services:
  api:
    build: 
      context: node
    container_name: api_node
    image: api_node
    volumes:
      - ./node:/api
    ports:
      - "3000:3000"
    networks:
      - gabrielNet
    depends_on:
      postgres_api:
        condition: service_healthy
  
  nginx:
    restart: always
    container_name: nginx
    build: 
      dockerfile: ./nginx.dockerfile
      context: nginx
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - gabrielNet

  postgres_api:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - gabrielNet
       
networks:
  gabrielNet:
    driver: bridge

volumes:
  pgdata:
    