version: '3'
services:
  api:
    build: 
      dockerfile: ./api.dockerfile
      context: .
    container_name: api_node
    image: api_node
    ports:
      - "3000:3000"
    networks:
      - gabrielNet
    depends_on:
      - postgres_api
  
  nginx:
    restart: always
    build: 
      dockerfile: ./nginx.dockerfile
      context: .
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - gabrielNet

  postgres_api:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    networks:
      - gabrielNet
   
networks:
  gabrielNet:
    driver: bridge
    